### ISSUE TITLE
ExpandCollapseState is not found

### ISSUE THREAD

**Issue by lublak** [Descolada/UIA-v2#1]
based on the example: https://github.com/Descolada/UIA-v2/blob/main/Examples/Example10_ExpandCollapsePattern.ahk

![grafik](https://user-images.githubusercontent.com/44057030/218265584-913fa7a9-c261-4793-9a5a-ce41a40c791a.png)

**Comment by Descolada** [comment]
I would actually recommend sticking to UIA, you will have better performance and reliability with that.
I noticed that you Acc code differs from UIA code - in one you are checking the state for "Konfiguration" element, but in UIA "Treiber" element instead. Are you sure you got the correct element in UIA?

1) Update UIA.ahk if you haven't already
2) Inspect the element with UIAViewer (run UIA.ahk alone), see if it has the ExpandCollapsePattern, and try double-clicking Expand() or Collapse() to check whether it's working
3) After using FindElement, make sure you found the correct one, using Highlight() or Dump() or DumpAll().
4) Check whether the found element has IsExpandCollapsePatternAvailable property as 1 (true).
5) If IsExpandCollapsePatternAvailable is 1 but you still get the error, try element.ExpandCollapsePattern.ExpandCollapseState instead (although it shouldn't make a difference, perhaps you've discovered an unknown bug?)

If Acc was able to get the expand-collapse state, then UIA should be able to as well...

**Comment by lublak** [comment]
Yes but currently i can not get UIA working. 
It false says that an element can not expand.
But acc can expand it.

1. done
2. No it doesnt have ExpandCollapsePattern
![grafik](https://user-images.githubusercontent.com/44057030/218266743-3ea582a2-a872-4fd2-ad6a-b0cf0e9a12e2.png)
3. Its the correct element
4. IsExpandCollapsePatternAvailable returns 0
5. (i mean IsExpandCollapsePatternAvailable  returns 0)
![grafik](https://user-images.githubusercontent.com/44057030/218267006-a343db59-2584-49e9-a5cb-156dafba1378.png)



Here are both examples

```ahk
; UIA not working
bdeadminEl := UIA.ElementFromHandle("BDE-Verwaltung  C:\Program Files (x86)\Common Files\Borland Shared\BDE\IDAPI32.CFG ahk_exe bdeadmin.exe")
bdeadminEl.FindElement({Name:"Konfiguration",Type:"TabItem"}).SetFocus()
tree := bdeadminEl.FindElement({Name: "Konfiguration", Type:"TreeItem"})
if tree.ExpandCollapseState == UIA.ExpandCollapseState.Collapsed {
    tree.Expand()
}
tree := bdeadminEl.FindElement({Name: "Treiber", Type:"TreeItem"})
if tree.ExpandCollapseState == UIA.ExpandCollapseState.Collapsed {
    tree.Expand()
}

tree := bdeadminEl.FindElement({Name: "Native", Type:"TreeItem"})
if tree.ExpandCollapseState == UIA.ExpandCollapseState.Collapsed {
    tree.Expand()
}
tree := bdeadminEl.FindElement({Name: "ORACLE", Type:"TreeItem"})
tree.SetFocus()

; ACC works fine
bdeadminEl := Acc.ElementFromHandle("BDE-Verwaltung  C:\Program Files (x86)\Common Files\Borland Shared\BDE\IDAPI32.CFG ahk_exe bdeadmin.exe")
bdeadminEl.FindElement({Name: "Konfiguration", Role: 37}).Select(Acc.SelectionFlag.TakeFocus)
tree := bdeadminEl.FindElement({Name: "Konfiguration", Role: 36})
if tree.State & Acc.State.Collapsed == Acc.State.Collapsed {
    tree.DoDefaultAction()
}
tree := bdeadminEl.FindElement({Name: "Treiber", Role: 36})
if tree.State & Acc.State.Collapsed == Acc.State.Collapsed {
    tree.DoDefaultAction()
}

tree := bdeadminEl.FindElement({Name: "Native", Role: 36})
if tree.State & Acc.State.Collapsed == Acc.State.Collapsed {
    tree.DoDefaultAction()
}
tree := bdeadminEl.FindElement({Name: "ORACLE", Role: 36})
tree.Select(Acc.SelectionFlag.TakeFocus)
```

**Comment by Descolada** [comment]
I think the only explanation is that BDE has implemented Acc properly, but there is some kind of problem in UIA-Acc conversion. A TreeItem should have the ExpandCollapsePattern available as well. 

```
bdeadminEl := UIA.ElementFromHandle("BDE-Verwaltung  C:\Program Files (x86)\Common Files\Borland Shared\BDE\IDAPI32.CFG ahk_exe bdeadmin.exe")
bdeadminEl.FindElement({Name:"Konfiguration",Type:"TabItem"}).SetFocus()
tree := bdeadminEl.FindElement({Name: "Konfiguration", Type:"TreeItem"})
if tree.LegacyIAccessibleState & 0x400  { ; 0x400 == Acc.State.Collapsed
    tree.DoDefaultAction()
}
tree := bdeadminEl.FindElement({Name: "Treiber", Type:"TreeItem"})
if tree.LegacyIAccessibleState & 0x400 {
    tree.DoDefaultAction()
}

tree := bdeadminEl.FindElement({Name: "Native", Type:"TreeItem"})
if tree.LegacyIAccessibleState & 0x400 {
    tree.DoDefaultAction()
}
tree := bdeadminEl.FindElement({Name: "ORACLE", Type:"TreeItem"})
tree.SetFocus()
```

This is not something UIA.ahk can work around/fix, so I'm closing this issue.

**Comment by lublak** [comment]
@Descolada LegacyIAccessibleState works fine for this.
Is UAI still faster with it?
A small feature request for Legacy stuff:
```ahk
UAI.Legacy.State with the same content as Acc.State
UAI.Legacy.State.Collapsed ; 0x400 
```

**Comment by Descolada** [comment]
These were added with commit b2d33b2dc32bfcd90b90a98eb540d849f0ca748e: `UIA.LegacyIAccessible.State.Collapsed`

**Comment by lublak** [comment]
@Descolada thanks 👍 
In any case, you could almost make this a standard feature of ahk so good are they.
With it, you can automate even the most insidious applications. Thanks!
