### ISSUE TITLE
UIA Browser confusing paths.

### ISSUE THREAD

**Issue by LAPIII** [Descolada/UIA-v2#12]
In Edge and on [this page](https://www.upperdeckepack.com/Store/FreePack) the library keeps confusing `Y/YYY/YqYYYYYYVR5u` with `Y/YYY/YqYYYYYYVR5u6`. The paths on this page change and the first is `Y/YYY/YqYYYYYYV5t`, which has the name `Select your item...` under `Daily Free Pack`. Neither properties nor the conditional path help.

In the Opera browser, the library does work correctly with the path for the element.

**Comment by Descolada** [comment]
I don't exactly understand the issue yet. 
`Y/YYY/YqYYYYYYV5t` should be `Select your item...` under `Daily Free Pack`
`Y/YYY/YqYYYYYYVR5u` should be the next products' `Link`-type element
`Y/YYY/YqYYYYYYVR5u6` should be the `Link`-type elements `Image`-type child

What gets confused with what? What is the expected result? What is your goal?

**Comment by LAPIII** [comment]
Since then they had changed things around. It was getting `Y/YYY/YqYYYYYYV5t` confused with `Y/YYY/YqYYYYYYVR5u`. Today `cUIA.WaitElementFromPath("Y/YYY/YqYYYYYYV5t")`  will work with `Click()` and `Highlight()` will highlight about the elements location which I think is its location when the elements are halfway loaded. In Opera it works perfectly.
