### ISSUE TITLE
Alpha version breaks UIA - just an FYI

### ISSUE THREAD

**Issue by AardCrowley** [Descolada/UIA-v2#13]
![image](https://github.com/Descolada/UIA-v2/assets/12467582/63a91a05-e27a-4ecc-8169-49c4bd4c99fd)

See the above. It only breaks in the alpha version, which I've uninstalled for the time being. Just giving you a head's up so you can prevent issues down the road if/when the alpha version becomes live.

**Comment by Descolada** [comment]
How did you even get to that error? I get a runtime error for `static ReservedNotSupportedValue` of
```
Not a valid method, class or property definition.
     Specifically: ReservedNotSupportedValue
```

**Comment by Descolada** [comment]
Fixed.
