### ISSUE TITLE
I cannot login at Bitdefender.

### ISSUE THREAD

**Issue by LAPIII** [Descolada/UIA-v2#17]
I cannot get the text field element at the sign in page redirected from `https://login.bitdefender.com/central`. I have tried several browsers, Edge, Chrome, Opera, Firefox. The ACCViewer can detect the Email text field.  If I need UIA Access, then please help me as I don't know how to make it.

**Comment by Descolada** [comment]
Unable to reproduce, running Windows 10, latest UIA, latest Chrome, AHK without UIAccess:
![image](https://github.com/Descolada/UIA-v2/assets/16986957/cff2a82d-73a8-4b7a-b8c2-e03971c52910)
