### ISSUE TITLE
What I want to do with If / Else.

### ISSUE THREAD

**Issue by LAPIII** [Descolada/UIA-v2#18]
What I would like to do is to login to a site, but first check if I'm logged in already. Here's an example:

```
#SingleInstance Force
#Requires Autohotkey v2.0+
#Include <UIA>
#Include <UIA_Browser>
Run "chrome.exe https://google.com"
WinWaitActive "ahk_exe chrome.exe"
cUIA := UIA_Browser()
cUIA.ElementFromHandle()

if button := cUIA.ElementFromPathExist("VR0/")	; Name:"Google Account: Luis Piña III" button
button.Click()
else
cUIA.WaitElementFromPath("V5t").Click()		; Name:"Sign in"
```

Can what I want to do be done? If not then could you please consider adding something to this function to make it do so?

**Comment by Descolada** [comment]
That is how you would do it, yes. You might also want to check the Name of the found element to check whether it actually is the correct one: 
```
if (button := cUIA.ElementFromPathExist("VR0/")) && InStr(button.Name, "Google Account")
    button.Click() ; already logged in
else if (button := cUIA.ElementFromPathExist("VR0/")) && (button.Name == "Sign in)
    button.Click() ; click Sign in
```

GitHub *issues* is meant for issues with UIA-v2 or concrete feature request, not help requests. Please post your help requests on the AutoHotkey forums or Discord.
