### ISSUE TITLE
UIAViewer not working in Windows7

### ISSUE THREAD

**Issue by elkmug** [Descolada/UIA-v2#23]
The main question is: Should it? Does UIA-v2 even officially support Windows7?
 
The example scripts I've experimented with work as expected so it seems like it does, but you never know unless you ask.

I've tried running UIA.ahk every way I can think of, as a regular user, as administrator, as administrator with UI access, but UIAViewer does not open. 

The cursor flashes a bit sometimes, but AHK doesn't error or complain in any way, so it's unclear what's up.

I've tried with both AHK 2.0.5 and 2.0.10. 

Am I missing something?

**Comment by Descolada** [comment]
Please try again with the latest UIA version, it should be fixed now. Note that a lot of UIA functionality is missing in Windows 7 because it was only introduced then.

**Comment by elkmug** [comment]
> Please try again with the latest UIA version, it should be fixed now. 

It is; Thank you!

>Note that a lot of UIA functionality is missing in Windows 7 

Understood. 

But, luckily UIA has been able to do what I've needed it to. 

And so far, the only issues I've had with UIAViewer have been with Firefox and per the UIA-v2 thread at the AHK forums that might just be due to the way Firefox handles tabs since, it will work OK if there aren't too many open.
