### ISSUE TITLE
UIATreeInspector: Hover mouse above an element to jump to tree-location?

### ISSUE THREAD

**Issue by Dxhs** [Descolada/UIA-v2#26]
I apologize if this already is a feature, but is it possible to have an "element picker-tool" of sorts? 

Ahk-Spy and similar had something like this where you would point the mouse to an element and jump to that element in the UIA Tree. 

I absolutely love your work with UIA-v2 and would love this as well as it would save much time when scripting. Currently I'm using the filter to narrow down the search, then select the correct element, then remove the filter.

**Comment by Descolada** [comment]
Just to confirm: you are aware of UIAViewer (opened via running UIA.ahk alone), the program you are automating isn't inspectable with it, and you specifically need to use UIATreeViewer?

**Comment by Dxhs** [comment]
Apologize, I was not... And both of my programs can be automated using this. Thanks a lot!
