### ISSUE TITLE
WalkTree issues (Windows 11)

### ISSUE THREAD

**Issue by Dxhs** [Descolada/UIA-v2#27]
Hello

The documentation says little about how well UIA works on Windows 11. So far everything works great, except for TreeWalker.

I have tried various methods of getting anything returned from TreeWalker, even tried the basic example in the documentation, but I always get the same error message: Error: No element found with GetNextSiblingElement.

Current attempt is this:

```
    chromeEl := UIA.ElementFromHandle("ahk_exe chrome.exe")
    ;try {
        WinGetPos(&X, &Y, &Width, &Height, "A")
        location := chromeEl.waitElement({Name:"Start"}).getpos()
        MouseMove(location.x+location.w/2, location.y+location.h/2, 0)
        Click

        start := chromeEl.waitElement({Name:"Favoritter"})
        location := chromeEl.FindElement({Name:"OIS300 Kundeordre. Åpne KO-funksjoner", startingElement: start}).getpos()
        MouseMove(location.x+10, location.y+location.h/2, 0)

        location2 := chromeEl.FindElement({Name:"OIS300 Kundeordre. Åpne KO-funksjoner", startingElement: start}).WalkTree("+2").getpos()
        distX := location.x - location2.x
        msgbox(distX)
```

Everything here works until i try to walk the tree.

**Comment by Descolada** [comment]
I'm still using Windows 10 and haven't updated the examples for Windows 11 in a while, so it might be that they are broken. I'll try to fix them once I get some time.

About the TreeWalking, there was recently a similar problem posed on the AHK forums and for some reason TreeWalkers with `UIA.TrueCondition` (the default for WalkTree) is broken in Chrome. I'm not sure when this happened but I'll submit a bug report eventually for it. In the meanwhile try using `WalkTree("+2", UIA.ContentViewWalker)` instead.

By the way, you can replace
```
        location := chromeEl.waitElement({Name:"Start"}).getpos()
        MouseMove(location.x+location.w/2, location.y+location.h/2, 0)
        Click
```
with
`chromeEl.waitElement({Name:"Start"}).Click("left")`

**Comment by Dxhs** [comment]
UIA.ContentViewCondition didn't work.

I thought WalkTree +n walked any item next in the tree. I might have misunderstood this. What I'm after is whatever the next item is, to calculate the distance between the list items in the browser. Nowadays it is `Name:"Kunderegister"`.

![image](https://github.com/Descolada/UIA-v2/assets/13475068/c3b812e7-c41d-4e01-a89d-8e70b5bb464c)

Aha `Click("left")`. That's nice, but it seems like there's no speed-setting. Can I just change `MouseMove(prevX, prevY)` to `MouseMove(prevX, prevY, 0)` in UIA.ahk?

**Comment by Descolada** [comment]
Well there's your problem: the highlighted element in the screenshot doesn't have any siblings, which means `WalkTree("+2")` will throw an error. One way would be to walk the tree another way: `WalkTree("p.+1.1")` which first walk to the parent element, then the next element over, and gets the first child. Alternatively you could use `WindowElement.FindElement({Type:"Text"},,,, startingElement)` to get the next Text-type element in the tree. 
If you haven't checked out my video tutorial series on Youtube, then you might get some additional info from there.

`Element.Click("left")` obeys SetDefaultMouseSpeed so you can use that to change the speed, although SendMode needs to be Event. Under the hood it uses pretty much the same technique you are using: `Click(location.x+location.w//2, location.y+location.h//2)`. Unfortunately Click doesn't have a speed parameter, so you'd need to rewrite the function to use MouseClick instead.

**Comment by Dxhs** [comment]
I see, there's one child per parent in the tree. But changing to `WalkTree("p.+1.1")` also throws the same error. Btw, the documentation (06. TreeWalker) uses comma `("p,+2,1")`, I tested that also (didn't work well heh). I'll check out your YouTube vids.

![image](https://github.com/Descolada/UIA-v2/assets/13475068/cfe82811-dddc-4f03-a572-672979b69d9d)

Might it be related to the Chrome problem you mentioned earlier?

```
1  ^R::
2  {
3      chromeEl := UIA.ElementFromHandle("ahk_exe chrome.exe")
4      ;try {
5          WinGetPos(&X, &Y, &Width, &Height, "A")
6          location := chromeEl.waitElement({Name:"Start"}).getpos()
7          MouseMove(location.x+location.w/2, location.y+location.h/2, 0)
8          Click
9  
10         start := chromeEl.waitElement({Name:"Favoritter"})
11         location := chromeEl.FindElement({Name:"OIS300 Kundeordre. Åpne KO-funksjoner", startingElement: start}).getpos()
12         MouseMove(location.x+10, location.y+location.h/2, 0)
13 
14         location2 := chromeEl.FindElement({Name:"OIS300 Kundeordre. Åpne KO-funksjoner", startingElement: start}).WalkTree("p.+1,1").getpos()
15         distX := location.x - location2.x
16         msgbox(distX)
17  
18         ...
```

**Comment by Descolada** [comment]
I'm not sure what the problem might be. I created a small test script and everything works as expected in both Windows 10 and Windows 11:
```
#include UIA.ahk
#Requires AutoHotkey v2

Run "chrome.exe autohotkey.com"
WinWaitActive("AutoHotkey ahk_exe chrome.exe")
winEl := UIA.ElementFromHandle("ahk_exe chrome.exe")
el := winEl.WaitElement({Name:"Documentation", Type:"Link"}, 5000).Highlight()
el.WalkTree("p.+1.1").Highlight()
```
Perhaps try calling `WalkTree` "step by step" and see what element it is returning you (thus trying to figure out which step is going wrong)? For example, `MsgBox location.WalkTree("p").Highlight().Dump()`

**Comment by Dxhs** [comment]
Ok, so I tried both your example and my own in another place in the same webapp in chrome. Both worked as expected. But none of them work in the other place. Strange. The trees looks structurally the same to me. Maybe you see something different? 

![image](https://github.com/Descolada/UIA-v2/assets/13475068/2f8bcbf5-c1ef-4e6b-8f4c-c3039e71109c)

Heres a step-by-step. Hope this is what you meant:

```
chromeEl := UIA.ElementFromHandle("ahk_exe chrome.exe")
el := chromeEl.WaitElement({Name:"OIS300 Kundeordre. Åpne KO-funksjoner", Type:"Text", startingElement: start}, 2000)

p0 := el.walktree("p0").DumpAll()
p1 := el.walktree("p1").DumpAll()
p2 := el.walktree("p2").DumpAll()
p3 := el.walktree("p3").DumpAll()

FileAppend("Parent 0: `n" . p0 . "`n`nParent 1:`n" . p1 . "`n`nParent 2:`n" . p2 . "`n`nParent 3:`n" . p3, "output18.01.2024.txt")
```

Output:

Parent 0: 
Type: 50020 (Text) Name: "OIS300 Kundeordre. Åpne KO-funksjoner" LocalizedType: "text"

Parent 1:
Type: 50020 (Text) Name: "OIS300 Kundeordre. Åpne KO-funksjoner" LocalizedType: "text"

Parent 2:
Type: 50007 (ListItem) LocalizedType: "list item"
1: Type: 50020 (Text) Name: "OIS300 Kundeordre. Åpne KO-funksjoner" LocalizedType: "text"

Parent 3:
Type: 50008 (List) LocalizedType: "list"
1: Type: 50007 (ListItem) LocalizedType: "list item"
1,1: Type: 50020 (Text) Name: "Artikkelregister" LocalizedType: "text"
2: Type: 50007 (ListItem) LocalizedType: "list item"
2,1: Type: 50020 (Text) Name: "Konfig og simulering. Åpne" LocalizedType: "text"
3: Type: 50007 (ListItem) LocalizedType: "list item"
3,1: Type: 50020 (Text) Name: "Artikkelfunksjoner" LocalizedType: "text"
4: Type: 50007 (ListItem) LocalizedType: "list item"
4,1: Type: 50020 (Text) Name: "OIS300 Kundeordre. Åpne KO-funksjoner" LocalizedType: "text"
5: Type: 50007 (ListItem) LocalizedType: "list item"
5,1: Type: 50020 (Text) Name: "Kunderegister" LocalizedType: "text"
6: Type: 50007 (ListItem) LocalizedType: "list item"
6,1: Type: 50020 (Text) Name: "Kundeordre linjearbeidsbenk" LocalizedType: "text"
7: Type: 50007 (ListItem) LocalizedType: "list item"
7,1: Type: 50020 (Text) Name: "Innkjøpsstatistikk" LocalizedType: "text"
8: Type: 50007 (ListItem) LocalizedType: "list item"
8,1: Type: 50020 (Text) Name: "Produktstruktur" LocalizedType: "text"

**Comment by Descolada** [comment]
As you can see, for some reason `p` returned you the same element, whereas `p2` returns the ListItem which you probably wanted to reach. This means that try whether `WalkTree("p2.+1.1")` works.

**Comment by Dxhs** [comment]
Great, now it works as inteded! Thanks a lot. 

Apologize for submitting an user error. I think I understand the docs better now too. The `searchPath` of WalkTree was somewhat unintuitive for me in the beginning.

**Comment by Dxhs** [comment]
Great, now it works as inteded! Thanks a lot. 

Apologize for submitting an user error. I think I understand the docs better now too. The `searchPath` of WalkTree was somewhat unintuitive for me in the beginning.
