### ISSUE TITLE
Is it possible to use approximate names in FindElement([{Name:"(.....)"}]) ?

### ISSUE THREAD

**Issue by Dxhs** [Descolada/UIA-v2#28]
I'm trying to access an element that is named "Up to `"P100222 - MTC 315 kVA (...)" (Alt + Up Arrow)"". 

This is the folder up button in Windows Explorer (Windows 11). "Up to" is always there, but obviously the target folder name changes. 

There is only one element called "Up to" in the file explorer (except for if there are files that contain "Up to", but they appear after the button I'm after in the UIA Tree, so it can be mitigated.

Currently I use WalkTree from Up Band and that works, but the question is still valid.

![image](https://github.com/Descolada/UIA-v2/assets/13475068/2504089a-8562-4886-836c-1e2a490541e1)

**Comment by Descolada** [comment]
You can use matchmode StartsWith or Substring: https://github.com/Descolada/UIA-v2/wiki/05.-Conditions#findelements-and-waitelement-conditions
Eg. `WinEl.FindElement({Name:"Up to", MatchMode:"Substring"})`
