### ISSUE TITLE
UIAViewer - Marco Creator Error

### ISSUE THREAD

**Issue by nperovic** [Descolada/UIA-v2#3]
I think the problem is probably related to whitespace, the folder name is `... /Nikola XXXX/...`

![image](https://user-images.githubusercontent.com/122501303/221632431-55c54853-4a57-47c6-b1f9-a4debacdeffa.png)

**Comment by Descolada** [comment]
Fixed with commit [34b1f67](https://github.com/Descolada/UIA-v2/commit/34b1f678ba50354ac61daab4255977d2dec63c6f)
