### ISSUE TITLE
Why is ScrollIntoView() in UIAViewer's Macro Creator, but not in the wiki.

### ISSUE THREAD

**Issue by LAPIII** [Descolada/UIA-v2#33]
I got an error when trying to use this method on [Spotify](https://accounts.spotify.com/en/login/), so please show me an example of how to use it.

**Comment by Descolada** [comment]
It's mentioned in the Wiki under [ScrollItem pattern](https://github.com/Descolada/UIA-v2/wiki/07.-Patterns#scrollitem-pattern) (although not documented further as it does what its name says - scrolls the item into view), and demonstrated in Example11_ScrollPatternScrollItemPattern.ahk. 

I tested the following in Spotify and it worked:
```
#Requires AutoHotkey v2
#include UIA.ahk

WinTitle := "ahk_exe spotify.exe"
WinActivate(WinTitle)
WinWaitActive(WinTitle)
winEl := UIA.ElementFromHandle(WinTitle)
winEl.FindElement({Name:"Recently played"}).ScrollIntoView()
```
