### ISSUE TITLE
Pycharm UI is not showing in UIA viewer

### ISSUE THREAD

**Issue by inSade-prog** [Descolada/UIA-v2#38]
i want to automate the process of activating pycharm with a product key but there is a problem uia viewer is not picking the ui like nothing not even title, name,  empty i dont know what to do please help!! i tried image search but it doest work when resolution is changed on other pc

as you can see in screen shot it is not picking "Activation Code" button (its a button i guess)

![Screenshot (1)](https://github.com/Descolada/UIA-v2/assets/140848630/a54626da-cb4c-45c9-9019-c11ff09b0724)

**Comment by Descolada** [comment]
Hello,
PyCharm apparently doesn't support UIAutomation. It implements accessibility through Java Accessibility Bridge which is supported by the popular screen readers, but UIAViewer nor Accessibility Insights implements it. See [this StackOverflow article](https://stackoverflow.com/questions/67138982/java-swing-based-windows-desktop-application-is-not-detected-by-accessibilityins) for more information. You could probably use the accessibility bridge to locate that element, but as far as I know there isn't any AHK library available to do that, so perhaps some other language (Python) would be more suitable. 

An alternative option could be using OCR, which is less reliable. An example using my [UWP OCR library](https://github.com/Descolada/OCR):
```
#Requires AutoHotkey v2
#include <OCR>

result := OCR.FromWindow("Licences")
found := result.FindString("Activation code")
result.Click(found)
```
