### ISSUE TITLE
Firefox freezes if fullscreen

### ISSUE THREAD

**Issue by Tyarel8** [Descolada/UIA-v2#4]
If you call `UIA_Browser("A")` when firefox is in fullscreen, firefox will freeze for at least a minute. Using `UIA.ElementFromHandle("A")` works until you do something with it, when it also freezes. Using `UIAViewer` is the same.
I don't really want to use UIA when firefox is in fullscreen, but it is annoying if I use it accidentally and have to wait.

**Comment by Descolada** [comment]
Hello,
This is a know problem with the current release version of Firefox - it has terrible UIA support and will sometimes completely freeze when interacted with UIA. The solution is to update Firefox to the [beta version](https://www.mozilla.org/en-US/firefox/channel/desktop/), which fixes this problem. 
Please report back whether this helped, I will keep this issue open until then.
