### ISSUE TITLE
[Feature request] Change hotkey for capturing

### ISSUE THREAD

**Issue by Dxhs** [Descolada/UIA-v2#42]
I can't use the inspector with F1 and Escape as hotkeys to start/stop capturing. An example of this is that Escape often closes the application I'm inspecting. I often personally change it to Home and End for start/stop by editing the file manually. During updates, a GUI based feature for this would be very welcomed.

![image](https://github.com/user-attachments/assets/6b0a7d33-c990-4848-ad7f-b90244fcb5bd)

**Comment by Descolada** [comment]
As the closing effect of Esc has annoyed me as well multiple times, I've now changed the hotkey to Alt+S for both start and stop. Currently I have no plans of adding a way to change the default hotkey(s), but pull requests for that are welcome.
