### ISSUE TITLE
UIA_Browser - Reload() reliability with Vivaldi -> fix by using ControlClick

### ISSUE THREAD

**Issue by emp-00** [Descolada/UIA-v2#47]
I have a small script using Reload() and a GetTab() afterwards (and I'm a Vivaldi user).

The script always works fine "the first time" but if I press my hotkey again to execute the script once more (after waiting e.g. 5 secs for the page being fully reloaded) - I very often get:
ERROR: UIA_Browser / currentTab := GetTab() failed.
No search phrase matches found

I found out that in this case the Vivaldi Reload button remains "selected", see this pic, Probably this causes the GetTab() to fail - it's supposed to get the currently active tab, but probably the Reload button remains "active", therefore this fails?
![image](https://github.com/user-attachments/assets/91bfc142-a147-481c-947e-d8a129de99d0)

I also found the fix for this issue: Using **ControlClick()** instead of **Click()** for the **Reload() function** does the job! Is there a possibility that this can be revised as such in UIA_Browser or does this cause incompatibility with other browsers? At least for Vivaldi ControlClick() seems to be the reliable solution for clicking buttons and tabs, Thanks for looking into this.

```
; Presses the Reload button
	Reload() { 
		this.GetCurrentReloadButton().ControlClick()
	}
```

**Comment by Descolada** [comment]
I was unable to reproduce your described problem in the latest Vivaldi version, but replaced with ControlClick anyway. You could perhaps try `this.ControlSend("{F5}")` instead as well, which might even be more reliable (and faster?). I can update the library if it turns out to be the case :)
