### ISSUE TITLE
Can't get timeout to work with walktree

### ISSUE THREAD

**Issue by Dxhs** [Descolada/UIA-v2#49]
I use the timeout parameter in other instances in the same script in the same way as this except for with walktree. Is there an issue with the way i use this line? Because it waits indefinitely.

`chromeEl.waitElement([{LocalizedType:"row", timeout: 2000}]).walktree("p1.+1.1")`

**Comment by Descolada** [comment]
I tested in Windows 10 Notepad and couldn't reproduce your described problem:
```
WinActivate "ahk_exe notepad.exe"
w := UIA.ElementFromHandle("ahk_exe notepad.exe")
w.WaitElement({Type:"Scrollbar", timeout:2000}).WalkTree("p1.+1.1").Highlight()
```

Also tried in latest Chrome on this same page:
```
WinActivate "ahk_exe chrome.exe"
w := UIA.ElementFromHandle("ahk_exe chrome.exe")
w.WaitElement({Type:"Button", IsOffscreen:0, Name:"Quote", timeout:2000}).WalkTree("p1.+1.1").Highlight()
```
Still couldn't reproduce.

**Comment by Dxhs** [comment]
That's good to hear (kind of). It suggests the problem lies with my usage of walktree in the webpage (factory ERP system). 

will test around a bit. The tree I'm walking is kinda messy and not being represented realistically in the tree inspector. There are hidden descendants everywhere, which forces me to work in the blind sort of.

**Comment by Descolada** [comment]
In that case you might want to write your own implementation of `Element.DumpAll()` which uses a TreeWalker instead of FindElements, so the tree would be easier to debug.
