### ISSUE TITLE
can i handle multiple chrome tabs?

### ISSUE THREAD

**Issue by dsanke** [Descolada/UIA-v2#52]
i want ahk process the background tabs, but not affect my current viewing tab.
i can see different class in UIATreeInspector, and i can access the background tab in it.
but i dont know how to deal with it using UIA, the ElementFromChromium will only get foreground tab.

could i walk throught all Chrome_RenderWidgetHostHWNDs(the have the same title, class and process, but different id in window info) and select the right one via Name of Property? then i can use FindElement or ElementFromPath to get my job done.

**Comment by Descolada** [comment]
As far as I know what you want can't be done reliably. The Chrome_RenderWidgetHostHWND controls might get destroyed at any time, or the UIA tree might, and not all tabs will even have that control. Maybe Chrome.ahk would work instead?
In Firefox it's possible to get info from inactive tabs, but I don't know whether it's also possible to interact with them.

**Comment by dsanke** [comment]
thanks for the answer.
