### ISSUE TITLE
Help With Getting Element Path

### ISSUE THREAD

**Issue by MatejGolian** [Descolada/UIA-v2#54]
Hello,

Probably it's very simple, but I can't figure it out.
I have the following code:
MainElement := UIA.ElementFromHandle("ahk_id " . WinGetID("A"))
KontaktElement := MainElement.FindElement({Name:"Kontakt 7", ClassName:"ni::qt::QuickWindow"})

My question is just, how can I get the path to the KontaktElement?
Alternatively, how would I get all the level 1 children of the KontaktElement object?

**Comment by Descolada** [comment]
Hello,
```
UIAPath := MainElement.GetUIAPath(KontaktElement)

Children := KontaktElement.Children ; returns element array
```

**Comment by MatejGolian** [comment]
Thank you, I knew it was easy. 🙂 👍
Have a great week...
