### ISSUE TITLE
README.md -> link to v2 instead of the v1 "main thread"

### ISSUE THREAD

**Issue by emp-00** [Descolada/UIA-v2#8]
Citing the current README.md: "If you have questions or issues, either post it in the [AutoHotkey forums' main thread](https://www.autohotkey.com/boards/viewtopic.php?f=6&t=104999)"

I was mislead by this link and posted a question related to this UIA-v2 repository version in the above v1 thread.

Proposal: Change the link to this thread which I think is the the "v2 main thread"?
https://www.autohotkey.com/boards/viewtopic.php?f=83&t=113065

Hoping this helps & keep up the GREAT work!! Loving it!

**Comment by Descolada** [comment]
Thanks, fixed. :)
